services:
  # Frontend (Agora sem expor a porta 3007 externamente)
  frontend:
    build:
      context: ./bi-front
      dockerfile: Dockerfile
    container_name: hubdoacoesfrontend
    ports:
      - 3007:3007
    environment:
      - NODE_ENV=production
    networks:
      - boraimpactar
    # Remova o "ports" (o Nginx agora redireciona a porta 80 para o frontend)

  # Backend (Mantém a configuração original, mas roteado via Nginx)
  backend:
    build:
      context: ./bi-back
      dockerfile: Dockerfile
    container_name: hubdoacoesbackend
    ports:
      - 3017:3017
    environment:
      DATABASE_URL: postgresql://docker:docker@postgres:5432/bi_banco
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - boraimpactar

  # PostgreSQL (Mantém a configuração original)
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: bi_banco
    volumes:
      - pgdata:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d bi_banco"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - boraimpactar

volumes:
  pgdata:

networks:
  boraimpactar:
    external: true
