### Testes para a API de `request`

# Buscar requests com filtro de categoria
GET http://localhost:3001/solicitacao?ong_Id=100

###
# Buscar solicitacoes com filtro
GET http://localhost:3001/search-solicitacao?page=-1&sort=
###
# Criar um novo request
POST http://localhost:3001/solicitacao
Content-Type: application/json

{
    "title": "TESTE28",
    "category": "UTENSILIOS",
    "urgency": "HIGH",
    "ong_Id": 100,
    "expirationDuration": "4 semanas"
}

###
# Atualizar um request existente
PUT http://localhost:3001/solicitacao?id=30
Content-Type: application/json

{
    "title": "QUARO2UPDATED",
    "category": "UTENSILIOS",
    "urgency": "HIGH",
    "quantity": 5,
    "ong_Id": 3,
    "expirationDuration": "4 semanas"
}

###
# Deletar um request
DELETE http://localhost:3001/solicitacao?id=29
Content-Type: application/json

### Testes para a API de `repasse`

# Buscar repasses da ong pelo ong_Id
GET http://localhost:3002/repasse?ong_Id=88

###
# Buscar repasse com filtro
GET http://localhost:3002/search-repasse

###
# Criar uma nova repasse
POST http://localhost:3002/repasse
Content-Type: application/json

{
    "title": "Manteiga",
    "category": "ALIMENTO",
    "description": "Cadeiras de escritório em bom estado",
    "ong_Id": 88
}

###
# Criar uma repasse com dados inválidos
POST http://localhost:3002/repasse
Content-Type: application/json

{
    "title": "Cachorro",
    "category": "ALIMENT",
    "ong_Id": 99
}

###
# Atualizar uma repasse existente
PUT http://localhost:3002/repasse?id=4
Content-Type: application/json

{
    "title": "mesa",
    "category": "UTENSILIOS",
    "ong_Id": 100
}

###
# Atualizar uma repasse inexistente
PUT http://localhost:3002/repasse?id=999
Content-Type: application/json

{
    "title": "Mesa",
    "category": "MOVEIS",
    "number": 2,
    "description": "Mesas de madeira"
}

###
# Deletar uma repasse existente
DELETE http://localhost:3002/repasse?id=3
Content-Type: application/json

###
# Deletar uma repasse inexistente
DELETE http://localhost:3002/repasse?id=999
Content-Type: application/json

